# Generated by Django 4.2.3 on 2023-07-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='update',
            new_name='updated',
        ),
    ]
