# Generated by Django 4.2.3 on 2023-07-31 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_interface_connected_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='interfaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='base.interface'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='connected_device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_device', to='base.device'),
        ),
    ]
