# Generated by Django 4.2.3 on 2023-08-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_interface_device_device_interfaces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='interfaces',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='connected_device',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='id',
        ),
        migrations.AddField(
            model_name='interface',
            name='connected_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_interface', to='base.device'),
        ),
        migrations.AddField(
            model_name='interface',
            name='interface_neib',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='base.interface'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='ip_adress',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='speed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
