# Generated by Django 4.2.3 on 2023-08-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_device_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='ip_address',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
