# Generated by Django 4.2.3 on 2023-08-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_device_num_interfaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='interface_neib',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='status',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='subnet_mask',
        ),
    ]
